using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Threading;
using System.Threading.Tasks;
using D = System.Collections.Generic.Dictionary<string,object>;

namespace HgssStrategyReader {
  sealed class Plan {
    public D Raw;public int[] Directions;public Dictionary<string,Plan> Branches;public Plan Continuation;public string Approach,TalkKind;
    public static Plan Parse(D raw){var root=new Plan{Raw=raw};var stack=new Stack<Plan>();stack.Push(root);while(stack.Count>0){var p=stack.Pop();p.Directions=Json.Array(Json.Require(p.Raw,"directions")).Select(v=>(int)Json.Integer(v,0,3,"direction")).ToArray();p.Approach=Json.Text(p.Raw,"approach");p.TalkKind=Json.Text(p.Raw,"talkKind");object branches=Json.Require(p.Raw,"branches");if(branches!=null){p.Branches=new Dictionary<string,Plan>(StringComparer.Ordinal);foreach(var kv in Json.RequireObject(branches)){var child=new Plan{Raw=Json.RequireObject(kv.Value)};p.Branches.Add(kv.Key,child);stack.Push(child);}}object continuation=Json.Get(p.Raw,"continuation");if(continuation!=null){p.Continuation=new Plan{Raw=Json.RequireObject(continuation)};stack.Push(p.Continuation);}}return root;}
    public IEnumerable<Plan> Children {get{return Continuation!=null?new[]{Continuation}:Branches!=null?Branches.Values.AsEnumerable():Enumerable.Empty<Plan>();}}
  }
  sealed class Validated {public D File;public Plan Plan;public Session Session;public int Starts,Nodes,Version;}
  sealed class Metrics {public long Total,Talks;public int Worst;public double Seconds;}
  sealed class ValidationFrame {public Session Session;public Plan Plan;public int Depth;public bool Advancing,Entered;public Metrics Local;public List<ValidationFrame> Children=new List<ValidationFrame>();public Metrics Result;}
  sealed class Validator {
    readonly GameModel game; public Validator(GameModel game){this.game=game;}
    static void Check(bool ok,string error){if(!ok)throw new InvalidDataException(error);}
    static BigInteger? Limit(D limits,string key){object v=Json.Get(limits,key);if(v==null||Convert.ToString(v,CultureInfo.InvariantCulture)=="")return null;string s=Convert.ToString(v,CultureInfo.InvariantCulture);Check(s.Length>0&&s.All(c=>c>='0'&&c<='9'),"Invalid search limit.");return BigInteger.Parse(s,CultureInfo.InvariantCulture);}
    static double Number(Plan p,string key){return Json.Number(Json.Require(p.Raw,key));}
    static bool Near(double actual,double expected){return !double.IsNaN(actual)&&!double.IsInfinity(actual)&&Math.Abs(actual-expected)<=1e-7*Math.Max(1,Math.Abs(expected));}
    public Validated Validate(D file,CancellationToken token,Action<string,int> progress){
      Check(Json.Text(file,"format")=="hgss-complete-strategy","Choose an exported complete-strategy JSON.");int version=(int)Json.Integer(Json.Require(file,"version"),1,2,"version");Check(Json.Text(file,"model")==BuildInfo.ModelId,"This strategy uses a different predictor model. Build the reader for the version that exported it.");Check(Json.Get(file,"searchReportedOptimal") is bool,"Missing search metadata.");var setup=Json.RequireObject(Json.Require(file,"setup"));var turns=Json.RequireObject(Json.Require(setup,"turns"));foreach(string k in new[]{"lastDirection","counter","inhibit","ability","leadLevel","flute","item","radio","secondChance"})Json.Require(turns,k);if(version==2)Json.RequireObject(Json.Require(setup,"finish"));
      var plan=Plan.Parse(Json.RequireObject(Json.Require(file,"plan")));var session=game.Create(setup,token,progress);var limits=Json.Obj(Json.Get(setup,"limits"));var maxTurns=Limit(limits,"maxTurns");var maxTalks=Limit(limits,"maxConversations");var root=new ValidationFrame{Session=session,Plan=plan};var stack=new Stack<ValidationFrame>();stack.Push(root);int covered=0,checkedNodes=0;uint targetSeed=GameModel.Jump(session.Seed,session.Target);
      var pattern=TurnPattern.Parse(Json.Get(setup,"turnPattern"));
      while(stack.Count>0){token.ThrowIfCancellationRequested();var f=stack.Peek();var p=f.Plan;int n=f.Session.Candidates.Count;
        if(!f.Entered&&pattern!=null&&(pattern.Scope=="all"||Number(p,"totalConversations")==0))pattern.ValidateBlock(p.Directions,f.Session.Config.Facing);
        if(!f.Entered){f.Entered=true;var after=f.Session;for(int i=0;i<p.Directions.Length;i+=128){after=game.ApplyTurns(after,p.Directions.Skip(i).Take(128),token);Check(after.Candidates.All(c=>c.Cycle<=session.Target),"A turn block passes the target for a possible start.");if(progress!=null)progress("branches",checkedNodes);}
          bool talking=p.Branches!=null||p.Continuation!=null;bool identify=version==1||p.TalkKind=="identify";f.Local=new Metrics{Seconds=version==2?(double)p.Directions.Length*n/session.Finish.TurnsPerSecond:0};
          if(talking){Check(Json.Require(p.Raw,"finalTurns")==null,"Invalid conversation endpoint.");Check(after.Config.Facing==session.TalkFacing,"A conversation does not face the follower.");
            if(version==2){Check((p.Branches!=null)!=(p.Continuation!=null),"A talk must have either response branches or one continuation.");Check(Json.Require(p.Raw,"approach")==null&&(identify||p.TalkKind=="advance"),"Invalid talk phase.");Check(!f.Advancing||!identify,"Identification cannot resume after finishing has started.");Check(!identify||p.Continuation==null,"Identification must include its response branches.");}else Check(p.Branches!=null&&p.Continuation==null,"Invalid legacy response branch.");
            if(identify){Check(!maxTurns.HasValue||p.Directions.Length<=maxTurns.Value,"A turn block exceeds the exported TF limit.");Check(!maxTalks.HasValue||f.Depth+1<=maxTalks.Value,"A path exceeds the exported identification conversation limit.");f.Local.Total=n;f.Local.Worst=1;}f.Local.Talks=n;
            var groups=game.Responses(after,token);Check(groups.All(g=>g.Next.All(c=>c.Cycle<=session.Target)),"A conversation passes the target for a possible start.");if(version==2){foreach(var t in groups.SelectMany(g=>g.Timings)){Check(t.Seconds.HasValue,"Unsupported interaction timing.");f.Local.Seconds+=t.Seconds.Value;}}
            if(p.Continuation!=null)f.Children.Add(new ValidationFrame{Session=after.With(groups.SelectMany(g=>g.Next).ToList()),Plan=p.Continuation,Depth=f.Depth+(identify?1:0),Advancing=f.Advancing||!identify});
            else {Check(p.Branches.Count==groups.Count&&groups.All(g=>p.Branches.ContainsKey(g.Key)),"The strategy is missing a possible response branch.");foreach(var g in groups)f.Children.Add(new ValidationFrame{Session=after.With(g.Next),Plan=p.Branches[g.Key],Depth=f.Depth+(identify?1:0),Advancing=f.Advancing||!identify});}
            foreach(var child in f.Children)stack.Push(child);continue;
          }
          Check(Json.Integer(Json.Require(p.Raw,"finalTurns"),0,0,"finalTurns")==0&&after.Candidates.All(c=>c.Cycle==session.Target&&c.Seed==targetSeed),"A path does not finish exactly at the target.");
          if(version==2){Check(Json.Require(p.Raw,"continuation")==null,"Invalid final continuation.");string approach=after.Config.Facing==2?"left":after.Config.Facing==0&&session.Finish.WallAbove?"bonk-left":"";Check(approach!=""&&p.Approach==approach,"The final facing does not support the saved Raikou approach.");if(approach=="bonk-left")f.Local.Seconds+=session.Finish.BonkSeconds*n;}
          covered+=n;
        }
        var result=new Metrics{Total=f.Local.Total+f.Children.Sum(c=>c.Result.Total),Talks=f.Local.Talks+f.Children.Sum(c=>c.Result.Talks),Worst=f.Local.Worst+(f.Children.Count==0?0:f.Children.Max(c=>c.Result.Worst)),Seconds=f.Local.Seconds+f.Children.Sum(c=>c.Result.Seconds)};
        Check(Number(p,"sampleCount")==n&&Number(p,"totalConversations")==result.Total&&Number(p,"conversations")==result.Worst&&Number(p,"averageConversations")==result.Total/(double)n,"Saved identification conversation totals are inconsistent.");
        if(version==2)Check(Number(p,"totalTalks")==result.Talks&&Near(Number(p,"averageTalks"),result.Talks/(double)n)&&Near(Number(p,"totalSeconds"),result.Seconds)&&Near(Number(p,"averageSeconds"),result.Seconds/n),"Saved finishing time or conversation totals are inconsistent.");
        f.Result=result;stack.Pop();checkedNodes++;if(progress!=null)progress("branches",checkedNodes);
      }
      Check(covered==session.Candidates.Count,"The strategy does not cover every possible start.");return new Validated{File=file,Plan=plan,Session=session,Starts=covered,Nodes=checkedNodes,Version=version};
    }
  }
  sealed class Policy {public int Id;public string Kind,Approach;public bool NaturalLeft;public int[] Directions;public Policy Next;public Dictionary<string,Policy> Branches;}
  sealed class Cursor {public Session Session;public Policy Policy;public bool Initial;}
  sealed class Block {public List<D> Steps=new List<D>(),Choices=new List<D>();public bool Terminal;public Cursor Waiting;public D Forecast;}
  sealed class StrategyEngine {
    public readonly GameModel Game;public Validated Loaded;public Cursor Root,Current;public Block Block;public int Revision;public string Filename;readonly Stack<Cursor> history=new Stack<Cursor>();
    public StrategyEngine(GameModel game){Game=game;}
    public static Policy Compile(Plan root,int version){var compiled=new Dictionary<Plan,Policy>();var interned=new Dictionary<string,Policy>(StringComparer.Ordinal);int serial=0;Func<string,Policy,Policy> intern=(key,p)=>{Policy old;if(interned.TryGetValue(key,out old))return old;p.Id=++serial;interned.Add(key,p);return p;};var stack=new Stack<Tuple<Plan,bool>>();stack.Push(Tuple.Create(root,false));while(stack.Count>0){var f=stack.Pop();var p=f.Item1;if(!f.Item2){stack.Push(Tuple.Create(p,true));foreach(var child in p.Children)stack.Push(Tuple.Create(child,false));continue;}bool end=p.Branches==null&&p.Continuation==null;bool natural=version==2&&end&&p.Approach=="left"&&p.Directions.LastOrDefault()==2;Policy node;if(end){string approach=version==2?p.Approach:"legacy";node=intern("finish:"+approach+":"+natural,new Policy{Kind="finish",Approach=approach,NaturalLeft=natural});}else if(p.Continuation!=null){var next=compiled[p.Continuation];node=intern("talk:"+next.Id,new Policy{Kind="talk",Next=next});}else {var branches=p.Branches.ToDictionary(k=>k.Key,k=>compiled[k.Value],StringComparer.Ordinal);var first=branches.Values.First();if(branches.Values.All(v=>v==first))node=intern("talk:"+first.Id,new Policy{Kind="talk",Next=first});else node=intern("observe:"+string.Join(",",branches.OrderBy(k=>k.Key,StringComparer.Ordinal).Select(k=>Json.Quote(k.Key)+":"+k.Value.Id)),new Policy{Kind="observe",Branches=branches});}if(p.Directions.Length>0)node=intern("turn:"+string.Join(",",p.Directions)+":"+natural+":"+node.Id,new Policy{Kind="turn",Directions=p.Directions,NaturalLeft=natural,Next=node});compiled[p]=node;}return compiled[root];}
    public static List<D> DirectionRuns(int[] dirs){var result=new List<D>();for(int i=0;i<dirs.Length;){int length=0,repeats=0,saved=0;for(int len=2;len<=64&&i+len*2<=dirs.Length;len++){int r=1;while(i+(r+1)*len<=dirs.Length&&dirs.Skip(i).Take(len).SequenceEqual(dirs.Skip(i+r*len).Take(len)))r++;if(r>=2&&(r-1)*len>saved){length=len;repeats=r;saved=(r-1)*len;}}if(length>0){result.Add(Json.Map("directions",dirs.Skip(i).Take(length).ToArray(),"repeats",repeats));i+=length*repeats;}else {if(result.Count>0&&Json.Int(result.Last(),"repeats")==1)result.Last()["directions"]=((int[])result.Last()["directions"]).Concat(new[]{dirs[i]}).ToArray();else result.Add(Json.Map("directions",new[]{dirs[i]},"repeats",1));i++;}}return result;}
    static D Span(Session s){return Json.Map("count",s.Candidates.Count,"first",s.Candidates.Min(c=>c.Cycle),"last",s.Candidates.Max(c=>c.Cycle));}
    public Block Project(Cursor cursor,CancellationToken token){var s=cursor.Session;var p=cursor.Policy;var block=new Block();if(cursor.Initial&&s.Arrival)block.Steps.Add(Json.Map("kind","entry"));while(p!=null){token.ThrowIfCancellationRequested();if(p.Kind=="turn"){int count=p.Directions.Length-(p.NaturalLeft?1:0);var ds=p.Directions.Take(count).ToArray();if(count>0)block.Steps.Add(Json.Map("kind","turn","count",count,"directions",ds,"runs",DirectionRuns(ds),"title",count+" turns in place"));if(p.NaturalLeft)block.Steps.Add(Json.Map("kind","approach"));s=Game.ApplyTurns(s,p.Directions,token);p=p.Next;}
        else if(p.Kind=="talk"||p.Kind=="observe"){var groups=Game.Responses(s,token);if(p.Kind=="observe"&&groups.Any(g=>!p.Branches.ContainsKey(g.Key)))throw new InvalidDataException("A response has no saved continuation.");var next=p.Kind=="talk"?p.Next:p.Branches[groups[0].Key];bool input=p.Kind=="observe"&&groups.Any(g=>p.Branches[g.Key]!=next);block.Steps.Add(Json.Map("kind",input?"observe":"talk","cues",!input&&groups.Count==1?groups[0].Cues.Select(c=>c.Data()).ToArray():new D[0],"anyResponse",!input&&groups.Count>1,"answer",groups.Any(g=>g.Cues.Any(c=>c.Text=="Answer Yes"||c.Text=="Answer No"))?(s.Answer=="yes"?"Yes":"No"):""));if(input){block.Choices=groups.Select(g=>Json.Map("key",g.Key,"cues",g.Cues.Select(c=>c.Data()).ToArray(),"count",g.Next.Count,"search",g.Label)).ToList();block.Waiting=new Cursor{Session=s,Policy=p};block.Forecast=Span(s);return block;}s=s.With(groups.SelectMany(g=>g.Next).ToList());p=next;}
        else if(p.Kind=="finish"){uint seed=GameModel.Jump(s.Seed,s.Target);if(s.Candidates.Any(c=>c.Cycle!=s.Target||c.Seed!=seed))throw new InvalidDataException("The displayed route does not reach the exact target.");block.Steps.Add(Json.Map("kind","finish","approach",p.Approach,"seed",GameModel.Hex(seed)));block.Terminal=true;block.Forecast=Span(s);return block;}else throw new InvalidDataException("Unsupported instruction.");}throw new InvalidDataException("Missing final instruction.");}
    public void Load(D file,string filename,CancellationToken token,Action<string,int> progress){var loaded=new Validator(Game).Validate(file,token,progress);var root=new Cursor{Session=loaded.Session,Policy=Compile(loaded.Plan,loaded.Version),Initial=true};var block=Project(root,token);token.ThrowIfCancellationRequested();Loaded=loaded;Root=Current=root;Block=block;Filename=filename;history.Clear();Revision++;}
    public D Choose(string key,int revision){if(revision!=Revision)throw new InvalidDataException("This response belongs to an earlier instruction.");if(Block==null||Block.Waiting==null||!Block.Choices.Any(c=>Json.Text(c,"key")==key))throw new InvalidDataException("Select one of the displayed responses.");var w=Block.Waiting;var g=Game.Responses(w.Session,CancellationToken.None).Single(c=>c.Key==key);var cursor=new Cursor{Session=w.Session.With(g.Next),Policy=w.Policy.Branches[key]};var block=Project(cursor,CancellationToken.None);history.Push(Current);Current=cursor;Block=block;Revision++;return View();}
    public D Back(){if(history.Count==0)throw new InvalidDataException("No earlier response.");var cursor=history.Peek();var block=Project(cursor,CancellationToken.None);history.Pop();Current=cursor;Block=block;Revision++;return View("Change the previous selection.");}
    public D Restart(){if(Loaded==null)throw new InvalidDataException("Open a strategy first.");var block=Project(Root,CancellationToken.None);Current=Root;Block=block;history.Clear();Revision++;return View("Restarted");}
    public D View(string notice=""){if(Loaded==null)return null;var s=Loaded.Session;var m=s.Context.Mon;var t=s.Config;var p=Loaded.Plan.Raw;string nickname=!string.IsNullOrEmpty(m.Nickname)?m.Nickname:!string.IsNullOrEmpty(m.SpeciesName)?m.SpeciesName:"Follower";return Json.Map("revision",Revision,"filename",Path.GetFileName(Filename),"path",Filename,"notice",notice,"selected",history.Count,"remaining",Current.Session.Candidates.Count,"startingAdvances",Block.Terminal?Current.Session.Candidates.Select(c=>c.Origin).Distinct().OrderBy(n=>n).ToArray():new long[0],"canBack",history.Count>0,"nickname",nickname,"seed",GameModel.Hex(s.Seed),"first",s.First,"last",s.Last,"target",s.Target,"verified",Loaded.Starts,"answer",s.Answer=="yes"?"Yes":"No","arrival",s.Arrival,"details",new[]{"HP "+m.HP+"/"+m.MaxHP+" · "+GameModel.StatusKey(m.Status)+" · mood "+m.Mood+" · friendship "+m.Friendship,"Checkpoint facing "+GameModel.Names[s.Context.PlayerFacing]+" · follower "+GameModel.Names[s.TalkFacing],"Second roll "+t.EncounterRate+"% · last direction "+GameModel.Names[t.LastDirection]+" · opposite counter "+t.Counter+" · completed checks "+t.Inhibit,"Ability effect "+t.Ability+" · level "+t.LeadLevel+" · flute "+t.Flute+" · rate item "+(t.Item?"yes":"no")+" · radio "+t.Radio,"Saved identification talks: "+Json.Number(p["averageConversations"]).ToString("F3",CultureInfo.InvariantCulture)+" average · "+Json.Text(p,"conversations")+" worst case"+(s.Finish!=null?" · "+Json.Number(p["averageTalks"]).ToString("F3",CultureInfo.InvariantCulture)+" total talks average":""),Json.Bool(Loaded.File,"searchReportedOptimal")?"Export reports minimum identification average proven within its settings. The reader verifies the route, not the optimality proof.":"Complete saved strategy. Minimum average was not proven when exported."},"steps",Block.Steps,"terminal",Block.Terminal,"choices",Block.Choices,"forecast",Block.Forecast);}
  }
  static class AppStorage {public static string Home=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"HGSSStrategyReader");}
  // All work stays in this process. Cancellation and commit share a lock, so a
  // superseded import cannot replace the active strategy after cancellation.
  sealed class ReaderService : IDisposable {
    readonly object gate=new object();StrategyEngine engine;GameModel game;CancellationTokenSource pending;int generation;bool disposed;public Action<int,D> Progress;
    public Task Start(){return Task.Run(()=>{game=new GameModel();engine=new StrategyEngine(game);});}
    public void DiscardPendingLoads(){lock(gate){generation++;if(pending!=null)pending.Cancel();}}
    public Task<D> Send(string op,D args=null){if(op=="init")return Task.FromResult(Json.Map("ok",true,"emotes",game.Emotes));if(op=="cancel"){DiscardPendingLoads();return Task.FromResult(Json.Map("ok",true));}int ticket;CancellationToken token;lock(gate){if(disposed)throw new ObjectDisposedException("Reader");if(op=="open"){if(pending!=null)pending.Cancel();pending=new CancellationTokenSource();}ticket=++generation;token=pending==null?CancellationToken.None:pending.Token;}
      return Task.Run(()=>{try{if(op=="open"){string path=Json.Text(args,"path");var candidate=new StrategyEngine(game);var last=DateTime.UtcNow;candidate.Load(Json.Obj(Json.Get(args,"document"))??Json.Parse(File.ReadAllText(path)),path,token,(stage,count)=>{if((DateTime.UtcNow-last).TotalMilliseconds<50)return;last=DateTime.UtcNow;if(Progress!=null)Progress(ticket,Json.Map("stage",stage,"checked",count));});lock(gate){token.ThrowIfCancellationRequested();if(disposed||ticket!=generation)throw new OperationCanceledException();candidate.Revision=engine.Revision+1;engine=candidate;return Json.Map("ok",true,"view",engine.View());}}
        lock(gate){if(disposed)throw new ObjectDisposedException("Reader");D view;switch(op){case "choose":view=engine.Choose(Json.Text(args,"key"),Json.Int(args,"revision"));break;case "back":view=engine.Back();break;case "restart":view=engine.Restart();break;default:throw new InvalidDataException("Unknown reader action.");}return Json.Map("ok",true,"view",view);}}
        catch(Exception e){return Json.Map("ok",false,"error",e is OperationCanceledException?"Loading cancelled.":e.Message);}});
    }
    public void Dispose(){lock(gate){disposed=true;generation++;if(pending!=null)pending.Cancel();}}
  }
}
